apiVersion: v1
kind: Namespace
metadata:
  name: rancher

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  namespace: rancher
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - name: rancher-demo
        image: bashofmann/rancher-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        env:
          - name: COW_COLOR
            value: purple
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-service
  namespace: rancher
spec:
  selector:
    app: rancher-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
